### ISSUE TITLE
fadeoutDuration

### ISSUE THREAD

**Issue by zvjerka24** [zipme/RQShineLabel#9]
There is a property fadeoutDuration but doesn't have any impact on animation and it is not used anywhere in code. As a workaround I'm using shineDuration instead.

**Comment by zipme** [comment]
Sorry about that, should be fixed now!

**Comment by zvjerka24** [comment]
Thanks!

**Comment by cerupcat** [comment]
This is still an issue since startAnimationWithDuration is always using the self.shineDuration rather than the duration that's being passed in.
